### ISSUE TITLE
Change Add Activity Plus button to more visible green

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-django#81]
Change Add Activity Plus button to more visible green

**Comment by chuyachia** [comment]
[branch issue81](/joatuapp/joatu-django/tree/issue81) 
- Used fontawesome for the button and changed the color to green
- Added white-space: nowrap to the button so that texts are not pushed to two lines on smaller screens.
![issue81_1](https://user-images.githubusercontent.com/25123789/43358753-9472f748-9264-11e8-9358-141a0c805c1d.png)
- Added display:inline-block to the button so that it stays on the same line as its sibling
Before: button not on the same line
![issue81_2](https://user-images.githubusercontent.com/25123789/43358764-c9bc7708-9264-11e8-82ab-2af520ca9086.png)
After: button on the same line
![issue81_3](https://user-images.githubusercontent.com/25123789/43358775-e7c26582-9264-11e8-837a-41c8959c4d87.png)
